# Generated by Django 3.1.1 on 2020-09-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipe_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measurement',
            new_name='dimension',
        ),
    ]
