# Generated by Django 3.1.1 on 2020-09-09 15:25
import csv

from django.db import migrations


def upload_ingredients(apps, schema_editor, csv_file='ingredients.csv'):
    Ingredient = apps.get_model('recipes', 'Ingredient')
    old_data = Ingredient.objects.all()
    old_data.delete()
    data = csv.reader(open(csv_file, encoding='utf-8'), delimiter=',')
    try:
        obj_list = [
            Ingredient(
                id=id,
                title=row[0],
                dimension='г' if row[1] == '' else row[1],
            )
            for id, row in enumerate(data)
        ]
    except (IndexError):
        return 'IndexError'

    Ingredient.objects.bulk_create(obj_list)


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20200909_1443'),
    ]

    operations = [
        migrations.RunPython(upload_ingredients),
    ]
