# Generated by Django 3.1.1 on 2020-09-10 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20200910_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_amount', to='recipes.recipe'),
        ),
    ]
