# Generated by Django 3.1.1 on 2020-09-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Уникальный адрес'),
        ),
    ]
