# Generated by Django 3.1.1 on 2020-09-12 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_auto_20200912_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
