# Generated by Django 3.1.1 on 2020-09-12 22:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин')], max_length=22, null=True, verbose_name='Теги'),
        ),
    ]
